### ISSUE TITLE
Flutter 图标 - 自定义App的图标

### ISSUE THREAD

**Issue by yuxino** [yuxino/notes#91]
如果想要更换工程的图标。最直接的方法就是替换掉`ios`和`android`目录下面的图标。不过那样太麻烦了。。而且格式也好多。

于是谷歌了一下解决方案。找到了这一篇[How to change the application launcher icon on Flutter?](https://stackoverflow.com/questions/43928702/how-to-change-the-application-launcher-icon-on-flutter?answertab=votes#tab-top)。最高票的答案推荐的库是[flutter_launcher_icons](https://github.com/fluttercommunity/flutter_launcher_icons)。

用法很简单只需要在工程下面的`pubspec.yaml`加上配置。

``` yml
dev_dependencies: 
  flutter_launcher_icons: "^0.7.2"
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
```

重新`flutter pub get`一下更新依赖。或者直接用Android studio点一下更新就完成了安装。 

`image_path`是图标的地址。随便找一张图丢到对应就好了。

运行`flutter pub pub run flutter_launcher_icons:main`。

重新启动APP就能看到图标啦。 

如果想给`andorid`和`ios`配置不同的图标也是可以的，传一个`image_path`就行了。
